/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Secciones.Menu;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author Sofia Useche
 */
public class Adicionales extends javax.swing.JPanel {

    /**
     * Creates new form Adicionales
     */
    public Adicionales() {
        initComponents();
        configurarBoton(BotonRellena, "Rellena", "/rellena-.jpg","", "$2500");
        configurarBoton(BotonPapaFrancesa, "Papa a la francesa", "/papas-a-la-francesa-.jpg","", "$5000");
        configurarBoton(BotonEnvuelto, "Envuelto de mazorca", "/envueltos-de-mazorca-.jpeg","", "$2500");
        configurarBoton(BotonPapaYuca, "Porcion de papa y yuca", "/porcion-papa-y-yuca.jpeg","", "$4500");
        configurarBoton(BotonArroz, "Porcion de arroz", "/porcion-arroz-.png","", "$3000");
        configurarBoton(BotonPlatano, "Platano relleno", "/platano-relleno-.jpg","", "$4500");
        configurarBoton(BotonPatacon, "Porcion de patacon", "/patacones-.jpg","", "$4500");
        configurarBoton(BotonMazorca, "Mazorca chorriada", "/mazorca-chorreada-.jpeg","", "$2500");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    private void configurarBoton(javax.swing.JButton boton, String texto, String urlImagen, String precio, String descripcion) {
        boton.setIcon(icono(urlImagen, 143, 120)); 
        boton.setText("<html>\n    <div style=\"text-align: center; margin-top: 10px;\">\n"
                    + "        <font style=\"font-size:12px;\"><b>" + texto + "</b></font>\n"
                    + "        </div>\n"
                    + "        <div style=\"text-align: center; margin-top: 10px;\">\n"
                    + "        <font style=\"font-size:12px;\"><b>" + descripcion + "</b></font>\n"
                    + "        </div>\n" 
                +"<div style=\"text-align: center; margin-top: 10px;\">\n"
                    + "        <font style=\"font-size:10px;\">" + precio + "</font>\n"
                    + "    </div>\n</html>");
        boton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM); 
        boton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    }
    
    public Icon icono(String url, int ancho, int alto) {
    ImageIcon img = new ImageIcon(getClass().getResource(url));
    return new ImageIcon(img.getImage().getScaledInstance(ancho, alto, Image.SCALE_SMOOTH));
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Buttons_Adicionales = new javax.swing.JPanel();
        BotonRellena = new javax.swing.JButton();
        BotonPapaFrancesa = new javax.swing.JButton();
        BotonEnvuelto = new javax.swing.JButton();
        BotonPapaYuca = new javax.swing.JButton();
        BotonArroz = new javax.swing.JButton();
        BotonPlatano = new javax.swing.JButton();
        BotonPatacon = new javax.swing.JButton();
        BotonMazorca = new javax.swing.JButton();

        jScrollPane1.setBorder(null);

        Buttons_Adicionales.setBackground(new java.awt.Color(204, 204, 204));

        BotonRellena.setBackground(new java.awt.Color(255, 255, 255));
        BotonRellena.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        BotonRellena.setForeground(new java.awt.Color(0, 0, 0));
        BotonRellena.setBorder(javax.swing.BorderFactory.createMatteBorder(15, 15, 15, 15, new java.awt.Color(255, 255, 255)));
        BotonRellena.setBorderPainted(false);
        BotonRellena.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonRellena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRellenaActionPerformed(evt);
            }
        });

        BotonPapaFrancesa.setBackground(new java.awt.Color(255, 255, 255));
        BotonPapaFrancesa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        BotonPapaFrancesa.setForeground(new java.awt.Color(0, 0, 0));
        BotonPapaFrancesa.setBorder(javax.swing.BorderFactory.createMatteBorder(15, 15, 15, 15, new java.awt.Color(255, 255, 255)));
        BotonPapaFrancesa.setBorderPainted(false);
        BotonPapaFrancesa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonPapaFrancesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonPapaFrancesaActionPerformed(evt);
            }
        });

        BotonEnvuelto.setBackground(new java.awt.Color(255, 255, 255));
        BotonEnvuelto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        BotonEnvuelto.setForeground(new java.awt.Color(0, 0, 0));
        BotonEnvuelto.setBorder(javax.swing.BorderFactory.createMatteBorder(15, 15, 15, 15, new java.awt.Color(255, 255, 255)));
        BotonEnvuelto.setBorderPainted(false);
        BotonEnvuelto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonEnvuelto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonEnvueltoActionPerformed(evt);
            }
        });

        BotonPapaYuca.setBackground(new java.awt.Color(255, 255, 255));
        BotonPapaYuca.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        BotonPapaYuca.setForeground(new java.awt.Color(0, 0, 0));
        BotonPapaYuca.setBorder(javax.swing.BorderFactory.createMatteBorder(15, 15, 15, 15, new java.awt.Color(255, 255, 255)));
        BotonPapaYuca.setBorderPainted(false);
        BotonPapaYuca.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonPapaYuca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonPapaYucaActionPerformed(evt);
            }
        });

        BotonArroz.setBackground(new java.awt.Color(255, 255, 255));
        BotonArroz.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        BotonArroz.setForeground(new java.awt.Color(0, 0, 0));
        BotonArroz.setBorder(javax.swing.BorderFactory.createMatteBorder(15, 15, 15, 15, new java.awt.Color(255, 255, 255)));
        BotonArroz.setBorderPainted(false);
        BotonArroz.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonArroz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonArrozActionPerformed(evt);
            }
        });

        BotonPlatano.setBackground(new java.awt.Color(255, 255, 255));
        BotonPlatano.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        BotonPlatano.setForeground(new java.awt.Color(0, 0, 0));
        BotonPlatano.setBorder(javax.swing.BorderFactory.createMatteBorder(15, 15, 15, 15, new java.awt.Color(255, 255, 255)));
        BotonPlatano.setBorderPainted(false);
        BotonPlatano.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonPlatano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonPlatanoActionPerformed(evt);
            }
        });

        BotonPatacon.setBackground(new java.awt.Color(255, 255, 255));
        BotonPatacon.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        BotonPatacon.setForeground(new java.awt.Color(0, 0, 0));
        BotonPatacon.setBorder(javax.swing.BorderFactory.createMatteBorder(15, 15, 15, 15, new java.awt.Color(255, 255, 255)));
        BotonPatacon.setBorderPainted(false);
        BotonPatacon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonPatacon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonPataconActionPerformed(evt);
            }
        });

        BotonMazorca.setBackground(new java.awt.Color(255, 255, 255));
        BotonMazorca.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        BotonMazorca.setForeground(new java.awt.Color(0, 0, 0));
        BotonMazorca.setBorder(javax.swing.BorderFactory.createMatteBorder(15, 15, 15, 15, new java.awt.Color(255, 255, 255)));
        BotonMazorca.setBorderPainted(false);
        BotonMazorca.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonMazorca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonMazorcaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Buttons_AdicionalesLayout = new javax.swing.GroupLayout(Buttons_Adicionales);
        Buttons_Adicionales.setLayout(Buttons_AdicionalesLayout);
        Buttons_AdicionalesLayout.setHorizontalGroup(
            Buttons_AdicionalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Buttons_AdicionalesLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(Buttons_AdicionalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Buttons_AdicionalesLayout.createSequentialGroup()
                        .addComponent(BotonRellena, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                        .addGap(17, 17, 17)
                        .addComponent(BotonPapaFrancesa, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                        .addGap(17, 17, 17)
                        .addComponent(BotonEnvuelto, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                        .addGap(17, 17, 17)
                        .addComponent(BotonPapaYuca, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE))
                    .addGroup(Buttons_AdicionalesLayout.createSequentialGroup()
                        .addComponent(BotonArroz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(17, 17, 17)
                        .addComponent(BotonPlatano, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(17, 17, 17)
                        .addComponent(BotonPatacon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(17, 17, 17)
                        .addComponent(BotonMazorca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(24, 24, 24))
        );
        Buttons_AdicionalesLayout.setVerticalGroup(
            Buttons_AdicionalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Buttons_AdicionalesLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(Buttons_AdicionalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BotonRellena, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonPapaFrancesa, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonEnvuelto, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonPapaYuca, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(Buttons_AdicionalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BotonArroz, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonPlatano, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonPatacon, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonMazorca, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
        );

        jScrollPane1.setViewportView(Buttons_Adicionales);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BotonArrozActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonArrozActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonArrozActionPerformed

    private void BotonPataconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonPataconActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonPataconActionPerformed

    private void BotonRellenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRellenaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonRellenaActionPerformed

    private void BotonPapaFrancesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonPapaFrancesaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonPapaFrancesaActionPerformed

    private void BotonEnvueltoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonEnvueltoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonEnvueltoActionPerformed

    private void BotonPapaYucaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonPapaYucaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonPapaYucaActionPerformed

    private void BotonPlatanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonPlatanoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonPlatanoActionPerformed

    private void BotonMazorcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonMazorcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonMazorcaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonArroz;
    private javax.swing.JButton BotonEnvuelto;
    private javax.swing.JButton BotonMazorca;
    private javax.swing.JButton BotonPapaFrancesa;
    private javax.swing.JButton BotonPapaYuca;
    private javax.swing.JButton BotonPatacon;
    private javax.swing.JButton BotonPlatano;
    private javax.swing.JButton BotonRellena;
    private javax.swing.JPanel Buttons_Adicionales;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
